os:
  - osx
  - linux

sudo: required

language: c

before_install:
  # Android SDK
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar xzf android-sdk_r23.0.2-linux.tgz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export ANDROID_HOME=$PWD/android-sdk-linux; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo y | android update sdk -a -t tools,platform-tools,extra-android-support,extra-android-m2repository,android-23,sys-img-armeabi-v7a-android-23,build-tools-19.0.1,extra-google-google_play_services,extra-google-m2repository --force --no-ui; fi
  # For 32bit tools like adb
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # Lets check if adb is works
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then adb version; fi

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python .travis/testandroid.py beforeScript; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python .travis/testandroid.py script; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python .travis/testios.py; fi
