// !!! DONT MODIFY THIS FILE DIRECTLY OR YOU WILL LOST THE CHANGE !!!
// THE FILE WAS GENERATED BY github.com/huxingyi/libphone/tools/phonelayout

#include "libphone.h"
#include "layout.h"

board *boardCreate(void) {
  board *page = (board *)calloc(1, sizeof(board));
  page->displayWidth = phoneGetViewWidth(0);
  page->displayHeight = phoneGetViewHeight(0);
  page->searchBar = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->searchBar, 0, 0, page->displayWidth, page->displayHeight * 0.0707338638373);
  phoneSetViewBackgroundColor(page->searchBar, 0x7b4655);
  page->tabBar = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->tabBar, 0, page->displayHeight * 0.0707338638373, page->displayWidth, page->displayHeight * 0.0707338638373);
  phoneSetViewBackgroundColor(page->tabBar, 0xfafafa);
  page->topHead = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->topHead, 0, page->displayHeight * 0.149425287356, page->displayWidth, page->displayHeight * 0.133952254642);
  phoneSetViewBackgroundColor(page->topHead, 0xd58395);
  page->topTitle = phoneCreateTextView(page->topHead, 0);
  phoneSetViewFontSize(page->topTitle, page->displayHeight * 0.0371206896552);
  phoneSetViewFontColor(page->topTitle, 0xffffff);
  phoneSetViewText(page->topTitle, "DAILY ACTIVITIES");
  phoneSetViewFontBold(page->topTitle, 1);
  phoneSetViewFrame(page->topTitle, 0, page->displayHeight * 0.022698938992, page->displayWidth, page->displayHeight * 0.0371206896552);
  page->infoPanel = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->infoPanel, 0, page->displayHeight * 0.283377541998, page->displayWidth, page->displayHeight * 0.36958443855);
  phoneSetViewBackgroundColor(page->infoPanel, 0xf7f5f5);
  page->firstInfoBox = phoneCreateContainerView(page->infoPanel, 0);
  phoneSetViewFrame(page->firstInfoBox, page->displayWidth * 0.0413793103448, page->displayHeight * 0.0141467727675, page->displayWidth * 0.441379310345, page->displayHeight * 0.153846153846);
  phoneSetViewBackgroundColor(page->firstInfoBox, 0xfafafa);
  phoneSetViewBorderColor(page->firstInfoBox, 0xdcaab5);
  phoneSetViewShadowColor(page->firstInfoBox, 0xdcaab5);
  phoneSetViewShadowRadius(page->firstInfoBox, page->displayWidth * 0.0206896551724);
  phoneSetViewShadowOffset(page->firstInfoBox, page->displayWidth * 0.00344827586207, page->displayHeight * 0.00221043324492);
  phoneSetViewCornerRadius(page->firstInfoBox, page->displayWidth * 0.0137862068966);
  phoneSetViewBorderWidth(page->firstInfoBox, dp(1));
  page->firstInfoNumber = phoneCreateTextView(page->firstInfoBox, 0);
  phoneSetViewFontSize(page->firstInfoNumber, page->displayHeight * 0.0580004420866);
  phoneSetViewFontColor(page->firstInfoNumber, 0x98646e);
  phoneSetViewText(page->firstInfoNumber, "10");
  phoneSetViewFontBold(page->firstInfoNumber, 1);
  phoneSetViewFrame(page->firstInfoNumber, 0, page->displayHeight * 0.0197179487179, page->displayWidth * 0.441379310345, page->displayHeight * 0.0580004420866);
  page->firstInfoDesc = phoneCreateTextView(page->firstInfoBox, 0);
  phoneSetViewFontSize(page->firstInfoDesc, page->displayWidth * 0.0506696551724);
  phoneSetViewFontColor(page->firstInfoDesc, 0x6e6e6b);
  phoneSetViewText(page->firstInfoDesc, "Registered Patients");
  phoneSetViewFontBold(page->firstInfoDesc, 1);
  phoneSetViewFrame(page->firstInfoDesc, 0, page->displayHeight * 0.0772338638373, page->displayWidth * 0.441379310345, page->displayHeight * 0.0649610963749);
  page->secondInfoBox = phoneCreateContainerView(page->infoPanel, 0);
  phoneSetViewFrame(page->secondInfoBox, page->displayWidth * 0.510344827586, page->displayHeight * 0.0141467727675, page->displayWidth * 0.441379310345, page->displayHeight * 0.153846153846);
  phoneSetViewBackgroundColor(page->secondInfoBox, 0xfafafa);
  phoneSetViewBorderColor(page->secondInfoBox, 0xdcaab5);
  phoneSetViewShadowColor(page->secondInfoBox, 0xdcaab5);
  phoneSetViewShadowRadius(page->secondInfoBox, page->displayWidth * 0.0206896551724);
  phoneSetViewShadowOffset(page->secondInfoBox, page->displayWidth * 0.00344827586207, page->displayHeight * 0.00221043324492);
  phoneSetViewCornerRadius(page->secondInfoBox, page->displayWidth * 0.0137862068966);
  phoneSetViewBorderWidth(page->secondInfoBox, dp(1));
  page->thirdInfoBox = phoneCreateContainerView(page->infoPanel, 0);
  phoneSetViewFrame(page->thirdInfoBox, page->displayWidth * 0.0413793103448, page->displayHeight * 0.185676392573, page->displayWidth * 0.441379310345, page->displayHeight * 0.153846153846);
  phoneSetViewBackgroundColor(page->thirdInfoBox, 0xfafafa);
  phoneSetViewBorderColor(page->thirdInfoBox, 0xdcaab5);
  phoneSetViewShadowColor(page->thirdInfoBox, 0xdcaab5);
  phoneSetViewShadowRadius(page->thirdInfoBox, page->displayWidth * 0.0206896551724);
  phoneSetViewShadowOffset(page->thirdInfoBox, page->displayWidth * 0.00344827586207, page->displayHeight * 0.00221043324492);
  phoneSetViewCornerRadius(page->thirdInfoBox, page->displayWidth * 0.0137862068966);
  phoneSetViewBorderWidth(page->thirdInfoBox, dp(1));
  page->forthInfoBox = phoneCreateContainerView(page->infoPanel, 0);
  phoneSetViewFrame(page->forthInfoBox, page->displayWidth * 0.510344827586, page->displayHeight * 0.185676392573, page->displayWidth * 0.441379310345, page->displayHeight * 0.153846153846);
  phoneSetViewBackgroundColor(page->forthInfoBox, 0xfafafa);
  phoneSetViewBorderColor(page->forthInfoBox, 0xdcaab5);
  phoneSetViewShadowColor(page->forthInfoBox, 0xdcaab5);
  phoneSetViewShadowRadius(page->forthInfoBox, page->displayWidth * 0.0206896551724);
  phoneSetViewShadowOffset(page->forthInfoBox, page->displayWidth * 0.00344827586207, page->displayHeight * 0.00221043324492);
  phoneSetViewCornerRadius(page->forthInfoBox, page->displayWidth * 0.0137862068966);
  phoneSetViewBorderWidth(page->forthInfoBox, dp(1));
  page->bottomHead = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->bottomHead, 0, page->displayHeight * 0.652961980548, page->displayWidth, page->displayHeight * 0.133952254642);
  phoneSetViewBackgroundColor(page->bottomHead, 0xd58395);
  page->bottomTitle = phoneCreateTextView(page->bottomHead, 0);
  phoneSetViewFontSize(page->bottomTitle, page->displayHeight * 0.0371206896552);
  phoneSetViewFontColor(page->bottomTitle, 0xffffff);
  phoneSetViewText(page->bottomTitle, "TOTAL ACTIVITIES");
  phoneSetViewFontBold(page->bottomTitle, 1);
  phoneSetViewFrame(page->bottomTitle, 0, page->displayHeight * 0.022698938992, page->displayWidth, page->displayHeight * 0.0371206896552);
  page->registrationPanel = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->registrationPanel, 0, page->displayHeight * 0.78691423519, page->displayWidth, page->displayHeight * 0.192086648983);
  phoneSetViewBackgroundColor(page->registrationPanel, 0xf7f5f5);
  return page;
}

