// !!! DONT MODIFY THIS FILE DIRECTLY OR YOU WILL LOST THE CHANGE !!!
// THE FILE WAS GENERATED BY github.com/huxingyi/libphone/tools/phonelayout

#include "libphone.h"
#include "layout.h"

board *boardCreate(void) {
  board *page = (board *)calloc(1, sizeof(board));
  page->displayWidth = phoneGetViewWidth(0);
  page->displayHeight = phoneGetViewHeight(0);
  page->searchBar = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->searchBar, dp(0), dp(0), dp(page->displayWidth), dp(page->displayHeight * 0.0625));
  phoneSetViewBackgroundColor(page->searchBar, 0x7b4655);
  page->tabBar = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->tabBar, dp(0), dp(page->displayHeight * 0.0625), dp(page->displayWidth), dp(page->displayHeight * 0.0625));
  phoneSetViewBackgroundColor(page->tabBar, 0xfafafa);
  page->padding = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->padding, dp(0), dp(page->displayHeight * 0.125), dp(page->displayWidth), dp(page->displayHeight * 0.00703125));
  page->topHead = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->topHead, dp(0), dp(page->displayHeight * 0.13203125), dp(page->displayWidth), dp(page->displayHeight * 0.118359375));
  phoneSetViewBackgroundColor(page->topHead, 0xd58395);
  page->appointmentPanel = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->appointmentPanel, dp(0), dp(page->displayHeight * 0.250390625), dp(page->displayWidth), dp(page->displayHeight * 0.3265625));
  phoneSetViewBackgroundColor(page->appointmentPanel, 0xf7f5f5);
  page->bottomHead = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->bottomHead, dp(0), dp(page->displayHeight * 0.576953125), dp(page->displayWidth), dp(page->displayHeight * 0.118359375));
  phoneSetViewBackgroundColor(page->bottomHead, 0xd58395);
  page->registrationPanel = phoneCreateContainerView(0, 0);
  phoneSetViewFrame(page->registrationPanel, dp(0), dp(page->displayHeight * 0.6953125), dp(page->displayWidth), dp(page->displayHeight * 0.3265625));
  phoneSetViewBackgroundColor(page->registrationPanel, 0xf7f5f5);
  return page;
}

